Contact Info<br/>
<p>Janet Howell<br/>
501 Elliott Street, Alexandria, LA 71301<br/>
318-442-8891 | FAX 318-442-8178 |
<script>
<!--

function escramble(){
 var a,b,c,d,e,f,g,h,i
 a='<a href=\"mai'
 b='janet.howell'
 c='\">'
 a+='lto:'
 b+='@'
 e='</a>'
 f=''
 b+='rpsb.us'
 g='<img src=\"'
 h=''
 i='\" alt="Email us." border="0">'

 if (f) d=f
 else if (h) d=g+h+i
 else d=b

 document.write(a+b+c+d+e)
}

escramble()

//-->

</script><br/></p>
